server: admin.ilike.com
port: 389
starttls: true
basedn: ou=people,dc=ilike,dc=com
rdn: uid
uidnumber_filter: '(uidNumber=*)'
gidnumber_default: 301
loginshell_default: /bin/bash
homedir_base: /srv/home
